In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_excel('DSSVK27GDQPAN.xlsx',index_col=None)
df.head()

,DANH SÁCH HỌC GDQP-AN KHÓA K27 ĐỢT 1 TỪ NGÀY 10/06 ĐẾN 06/07/2024 (HỌC LÝ THUYẾT TRƯỚC),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,TT,SL,TT lớp,Mã Sinh viên,Họ,Tên,Ngày Sinh,Giới \nTính,Nơi Sinh,LỚP \nSINH HOẠT,Đại đội,Tiểu đội,Phòng KTX\nở lại,HỌC LÝ THUYẾT\nHỌC TẠI CÁC PHÒNG HỌC C...,"HỌC THỰC HÀNH \n(ở lại tối, tập trung 2..."
1,1,1,1,27202201262,Dương Quốc Hoài,Ân,2003-08-20 00:00:00,Nữ,Gia Lai,K27QTM6,C1,a1,201,Học lý thuyết tại Trường ĐH. Duy tân cơ s...,Học thực hành tại Trường ĐH. Thể dục Thể th...
2,2,2,2,27212228975,Nguyễn Vũ Thiên,Bảo,2003-02-20 00:00:00,Nam,Quảng Nam,K27QTM6,C1,a1,406,Học lý thuyết tại Trường ĐH. Duy tân cơ s...,Học thực hành tại Trường ĐH. Thể dục Thể th...
3,3,3,3,27212240159,Nguyễn Thành,Chung,2003-03-18 00:00:00,Nam,Quảng Bình,K27QTM6,C1,a1,406,Học lý thuyết tại Trường ĐH. Duy tân cơ s...,Học thực hành tại Trường ĐH. Thể dục Thể th...
4,4,4,4,27212201242,Đoàn Vinh,Diệu,2003-06-10 00:00:00,Nam,Quảng Nam,K27QTM6,C1,a1,406,Học lý thuyết tại Trường ĐH. Duy tân cơ s...,Học thực hành tại Trường ĐH. Thể dục Thể th...

In [5]:
df = df.drop(df.columns[10:15],axis=1)
df.head()

,DANH SÁCH HỌC GDQP-AN KHÓA K27 ĐỢT 1 TỪ NGÀY 10/06 ĐẾN 06/07/2024 (HỌC LÝ THUYẾT TRƯỚC),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,TT,SL,TT lớp,Mã Sinh viên,Họ,Tên,Ngày Sinh,Giới \nTính,Nơi Sinh,LỚP \nSINH HOẠT
1,1,1,1,27202201262,Dương Quốc Hoài,Ân,2003-08-20 00:00:00,Nữ,Gia Lai,K27QTM6
2,2,2,2,27212228975,Nguyễn Vũ Thiên,Bảo,2003-02-20 00:00:00,Nam,Quảng Nam,K27QTM6
3,3,3,3,27212240159,Nguyễn Thành,Chung,2003-03-18 00:00:00,Nam,Quảng Bình,K27QTM6
4,4,4,4,27212201242,Đoàn Vinh,Diệu,2003-06-10 00:00:00,Nam,Quảng Nam,K27QTM6

In [6]:
df = df.drop(df.columns[0], axis=1)

In [7]:
df.head(10)

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,SL,TT lớp,Mã Sinh viên,Họ,Tên,Ngày Sinh,Giới \nTính,Nơi Sinh,LỚP \nSINH HOẠT
1,1,1,27202201262,Dương Quốc Hoài,Ân,2003-08-20 00:00:00,Nữ,Gia Lai,K27QTM6
2,2,2,27212228975,Nguyễn Vũ Thiên,Bảo,2003-02-20 00:00:00,Nam,Quảng Nam,K27QTM6
3,3,3,27212240159,Nguyễn Thành,Chung,2003-03-18 00:00:00,Nam,Quảng Bình,K27QTM6
4,4,4,27212201242,Đoàn Vinh,Diệu,2003-06-10 00:00:00,Nam,Quảng Nam,K27QTM6
5,5,5,27202235586,Mai Thị,Dung,2003-09-28 00:00:00,Nữ,Gia Lai,K27QTM6
6,6,6,27202201311,Nguyễn Thùy,Dung,2003-09-22 00:00:00,Nữ,Gia Lai,K27QTM6
7,7,7,27202227182,Nguyễn Thị Lê,Duyên,2003-10-03 00:00:00,Nữ,Quảng Nam,K27QTM6
8,8,8,27202224644,Nguyễn Võ Thùy,Duyên,2003-10-18 00:00:00,Nữ,Đà Nẵng,K27QTM6
9,9,9,27202227020,Lê Trần Gia,Hân,2003-11-27 00:00:00,Nữ,Đà Nẵng,K27QTM6

In [8]:
df.columns = ['Số lượng', 'Thứ tự lớp','Mã sinh viên', 'Họ', 'Tên', 'Ngày Sinh', 'Giới Tính', 'Nơi Sinh', 'Lớp sinh hoạt',]
df.head(10)

,Số lượng,Thứ tự lớp,Mã sinh viên,Họ,Tên,Ngày Sinh,Giới Tính,Nơi Sinh,Lớp sinh hoạt
0,SL,TT lớp,Mã Sinh viên,Họ,Tên,Ngày Sinh,Giới \nTính,Nơi Sinh,LỚP \nSINH HOẠT
1,1,1,27202201262,Dương Quốc Hoài,Ân,2003-08-20 00:00:00,Nữ,Gia Lai,K27QTM6
2,2,2,27212228975,Nguyễn Vũ Thiên,Bảo,2003-02-20 00:00:00,Nam,Quảng Nam,K27QTM6
3,3,3,27212240159,Nguyễn Thành,Chung,2003-03-18 00:00:00,Nam,Quảng Bình,K27QTM6
4,4,4,27212201242,Đoàn Vinh,Diệu,2003-06-10 00:00:00,Nam,Quảng Nam,K27QTM6
5,5,5,27202235586,Mai Thị,Dung,2003-09-28 00:00:00,Nữ,Gia Lai,K27QTM6
6,6,6,27202201311,Nguyễn Thùy,Dung,2003-09-22 00:00:00,Nữ,Gia Lai,K27QTM6
7,7,7,27202227182,Nguyễn Thị Lê,Duyên,2003-10-03 00:00:00,Nữ,Quảng Nam,K27QTM6
8,8,8,27202224644,Nguyễn Võ Thùy,Duyên,2003-10-18 00:00:00,Nữ,Đà Nẵng,K27QTM6
9,9,9,27202227020,Lê Trần Gia,Hân,2003-11-27 00:00:00,Nữ,Đà Nẵng,K27QTM6

In [9]:
df = df.drop(index = 0)
df.head(10)

,Số lượng,Thứ tự lớp,Mã sinh viên,Họ,Tên,Ngày Sinh,Giới Tính,Nơi Sinh,Lớp sinh hoạt
1,1,1,27202201262,Dương Quốc Hoài,Ân,2003-08-20 00:00:00,Nữ,Gia Lai,K27QTM6
2,2,2,27212228975,Nguyễn Vũ Thiên,Bảo,2003-02-20 00:00:00,Nam,Quảng Nam,K27QTM6
3,3,3,27212240159,Nguyễn Thành,Chung,2003-03-18 00:00:00,Nam,Quảng Bình,K27QTM6
4,4,4,27212201242,Đoàn Vinh,Diệu,2003-06-10 00:00:00,Nam,Quảng Nam,K27QTM6
5,5,5,27202235586,Mai Thị,Dung,2003-09-28 00:00:00,Nữ,Gia Lai,K27QTM6
6,6,6,27202201311,Nguyễn Thùy,Dung,2003-09-22 00:00:00,Nữ,Gia Lai,K27QTM6
7,7,7,27202227182,Nguyễn Thị Lê,Duyên,2003-10-03 00:00:00,Nữ,Quảng Nam,K27QTM6
8,8,8,27202224644,Nguyễn Võ Thùy,Duyên,2003-10-18 00:00:00,Nữ,Đà Nẵng,K27QTM6
9,9,9,27202227020,Lê Trần Gia,Hân,2003-11-27 00:00:00,Nữ,Đà Nẵng,K27QTM6
10,10,10,27202202880,Nguyễn Thị,Hoa,2003-01-03 00:00:00,Nữ,Đắk Lắk,K27QTM6

In [10]:
# Chuyển giá trị của cột đầu tiên thành số, giá trị không phải số sẽ thành NaN
df['Thứ tự lớp'] = pd.to_numeric(df['Thứ tự lớp'],errors='coerce')
df = df.dropna(subset=['Thứ tự lớp'])
df

,Số lượng,Thứ tự lớp,Mã sinh viên,Họ,Tên,Ngày Sinh,Giới Tính,Nơi Sinh,Lớp sinh hoạt
1,1,1.0,27202201262,Dương Quốc Hoài,Ân,2003-08-20 00:00:00,Nữ,Gia Lai,K27QTM6
2,2,2.0,27212228975,Nguyễn Vũ Thiên,Bảo,2003-02-20 00:00:00,Nam,Quảng Nam,K27QTM6
3,3,3.0,27212240159,Nguyễn Thành,Chung,2003-03-18 00:00:00,Nam,Quảng Bình,K27QTM6
4,4,4.0,27212201242,Đoàn Vinh,Diệu,2003-06-10 00:00:00,Nam,Quảng Nam,K27QTM6
5,5,5.0,27202235586,Mai Thị,Dung,2003-09-28 00:00:00,Nữ,Gia Lai,K27QTM6
...,...,...,...,...,...,...,...,...,...
8309,15,11.0,27212445210,Nguyễn Phạm Thuý,Trinh,2003-12-06 00:00:00,Nữ,Quảng Nam,K27PSU-QNH2
8310,15,12.0,27202445836,Bùi Thị Ngọc,Tuyền,2003-06-19 00:00:00,Nữ,Quảng Nam,K27PSU-QNH2
8311,15,13.0,27212422932,Ông Ích Thảo,Vân,2003-01-24 00:00:00,Nữ,Đà Nẵng,K27PSU-QNH2
8312,15,14.0,27212438633,Nguyễn Trần Hoàng,Vũ,2003-05-26 00:00:00,Nam,Quảng Nam,K27PSU-QNH2
8313,15,15.0,27202401145,Trần Thị Hải,Yến,2003-12-16 00:00:00,Nữ,Hà Tĩnh,K27PSU-QNH2

In [11]:
df = df.drop(df.columns[0],axis=1)
df

,Thứ tự lớp,Mã sinh viên,Họ,Tên,Ngày Sinh,Giới Tính,Nơi Sinh,Lớp sinh hoạt
1,1.0,27202201262,Dương Quốc Hoài,Ân,2003-08-20 00:00:00,Nữ,Gia Lai,K27QTM6
2,2.0,27212228975,Nguyễn Vũ Thiên,Bảo,2003-02-20 00:00:00,Nam,Quảng Nam,K27QTM6
3,3.0,27212240159,Nguyễn Thành,Chung,2003-03-18 00:00:00,Nam,Quảng Bình,K27QTM6
4,4.0,27212201242,Đoàn Vinh,Diệu,2003-06-10 00:00:00,Nam,Quảng Nam,K27QTM6
5,5.0,27202235586,Mai Thị,Dung,2003-09-28 00:00:00,Nữ,Gia Lai,K27QTM6
...,...,...,...,...,...,...,...,...
8309,11.0,27212445210,Nguyễn Phạm Thuý,Trinh,2003-12-06 00:00:00,Nữ,Quảng Nam,K27PSU-QNH2
8310,12.0,27202445836,Bùi Thị Ngọc,Tuyền,2003-06-19 00:00:00,Nữ,Quảng Nam,K27PSU-QNH2
8311,13.0,27212422932,Ông Ích Thảo,Vân,2003-01-24 00:00:00,Nữ,Đà Nẵng,K27PSU-QNH2
8312,14.0,27212438633,Nguyễn Trần Hoàng,Vũ,2003-05-26 00:00:00,Nam,Quảng Nam,K27PSU-QNH2
8313,15.0,27202401145,Trần Thị Hải,Yến,2003-12-16 00:00:00,Nữ,Hà Tĩnh,K27PSU-QNH2

In [13]:
df['Ngày Sinh'] = pd.to_datetime(df['Ngày Sinh'])
df['Ngày Sinh'] = df['Ngày Sinh'].dt.strftime('%d-%m-%Y')
df

,Thứ tự lớp,Mã sinh viên,Họ,Tên,Ngày Sinh,Giới Tính,Nơi Sinh,Lớp sinh hoạt
1,1.0,27202201262,Dương Quốc Hoài,Ân,20-08-2003,Nữ,Gia Lai,K27QTM6
2,2.0,27212228975,Nguyễn Vũ Thiên,Bảo,20-02-2003,Nam,Quảng Nam,K27QTM6
3,3.0,27212240159,Nguyễn Thành,Chung,18-03-2003,Nam,Quảng Bình,K27QTM6
4,4.0,27212201242,Đoàn Vinh,Diệu,10-06-2003,Nam,Quảng Nam,K27QTM6
5,5.0,27202235586,Mai Thị,Dung,28-09-2003,Nữ,Gia Lai,K27QTM6
...,...,...,...,...,...,...,...,...
8309,11.0,27212445210,Nguyễn Phạm Thuý,Trinh,06-12-2003,Nữ,Quảng Nam,K27PSU-QNH2
8310,12.0,27202445836,Bùi Thị Ngọc,Tuyền,19-06-2003,Nữ,Quảng Nam,K27PSU-QNH2
8311,13.0,27212422932,Ông Ích Thảo,Vân,24-01-2003,Nữ,Đà Nẵng,K27PSU-QNH2
8312,14.0,27212438633,Nguyễn Trần Hoàng,Vũ,26-05-2003,Nam,Quảng Nam,K27PSU-QNH2
8313,15.0,27202401145,Trần Thị Hải,Yến,16-12-2003,Nữ,Hà Tĩnh,K27PSU-QNH2

In [14]:
# Loại những sinh viên K28 ra khỏi danh sách
condition = df['Lớp sinh hoạt'].str.startswith('K27')
df = df[condition]
df

,Thứ tự lớp,Mã sinh viên,Họ,Tên,Ngày Sinh,Giới Tính,Nơi Sinh,Lớp sinh hoạt
1,1.0,27202201262,Dương Quốc Hoài,Ân,20-08-2003,Nữ,Gia Lai,K27QTM6
2,2.0,27212228975,Nguyễn Vũ Thiên,Bảo,20-02-2003,Nam,Quảng Nam,K27QTM6
3,3.0,27212240159,Nguyễn Thành,Chung,18-03-2003,Nam,Quảng Bình,K27QTM6
4,4.0,27212201242,Đoàn Vinh,Diệu,10-06-2003,Nam,Quảng Nam,K27QTM6
5,5.0,27202235586,Mai Thị,Dung,28-09-2003,Nữ,Gia Lai,K27QTM6
...,...,...,...,...,...,...,...,...
8309,11.0,27212445210,Nguyễn Phạm Thuý,Trinh,06-12-2003,Nữ,Quảng Nam,K27PSU-QNH2
8310,12.0,27202445836,Bùi Thị Ngọc,Tuyền,19-06-2003,Nữ,Quảng Nam,K27PSU-QNH2
8311,13.0,27212422932,Ông Ích Thảo,Vân,24-01-2003,Nữ,Đà Nẵng,K27PSU-QNH2
8312,14.0,27212438633,Nguyễn Trần Hoàng,Vũ,26-05-2003,Nam,Quảng Nam,K27PSU-QNH2
8313,15.0,27202401145,Trần Thị Hải,Yến,16-12-2003,Nữ,Hà Tĩnh,K27PSU-QNH2

In [16]:
df.to_csv('Danhsach_k27.csv',index=False)